# -*- coding: utf-8 -*-
"""TEQ Research Suite

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c8c-wCCU2LbazITnrkcM5tY5cWAbzCMI
"""

import pandas as pd
import requests
import math
import re
import io
import time
from typing import Dict, Any, List, Optional, Tuple

class TEQProjectEngine:
    """
    The core computational engine for the Title Efficiency Quotient (TEQ) Project.
    Designed for iterative hypothesis testing and empirical validation.
    """

    def __init__(self, baseline_csv_path: str):
        self.baseline_path = baseline_csv_path
        self.journal_baseline = self._load_source_of_truth()

        # Hypothesis 2.2 Configuration Constants
        self.TENSION_VERBS = {"weaponize", "subvert", "insulate", "disrupt", "exploit", "shatter", "enable", "circumvent"}
        self.NOVEL_TERMS = {
            "dark pattern": 1.5,
            "rational apathy": 1.5,
            "algorithm arbitration": 1.4,
            "closed loop": 1.3,
            "mail fraud": 1.2
        }

    def _load_source_of_truth(self) -> pd.DataFrame:
        """Loads and cleans the Washington & Lee Law Journal Rankings baseline."""
        try:
            # Using current LawJournals.csv format provided in the prompt
            df = pd.read_csv(self.baseline_path)
            # Rename based on the raw snippet observed (Rank, Name, Impact)
            df.columns = ['rank', 'journal_name', 'combined_score', 'impact_factor', 'journals', 'currency', 'cases']
            df['journal_name_clean'] = df['journal_name'].str.lower().str.strip()
            return df
        except Exception as e:
            print(f"Error loading Source of Truth: {e}")
            return pd.DataFrame()

    def get_journal_metadata(self, name: str) -> Dict[str, Any]:
        """Cross-references the Source of Truth for endogeneity controls."""
        match = self.journal_baseline[self.journal_baseline['journal_name_clean'] == name.lower().strip()]
        if not match.empty:
            return match.iloc[0].to_dict()
        return {"rank": "NR", "impact_factor": 0, "journal_name": name}

    def categorize_publication(self, title: str, author: str) -> Tuple[int, str]:
        """
        Categorization Schema:
        0: Flagship Article | 1: Essay | 2: Student Note/Comment
        3: Symposium/Invited | 4: Book Review | 5: Other (desc required)
        """
        t = str(title).lower()
        a = str(author).lower()

        # Rule for Student Notes (often anonymous or specifically labeled)
        if "anonymous" in a or any(k in t for k in ["note:", "comment:", "recent case", "recent legislation"]):
            return (2, "")

        # Rule for Symposium
        if any(k in t for k in ["symposium", "introduction:", "foreword", "afterword"]):
            return (3, "")

        # Rule for Book Reviews
        if "review:" in t or "review of" in t:
            return (4, "")

        # Rule for Essays
        if "essay:" in t:
            return (1, "")

        # Rule for "Other"
        others = ["tribute", "in memoriam", "colloquy", "response to", "preface", "letter"]
        for keyword in others:
            if keyword in t:
                return (5, keyword.capitalize())

        # Default to Flagship
        return (0, "")

    def calculate_teq_2_2(self, title: str, journal_rank: Any) -> float:
        """
        Executes Hypothesis 2.2:
        TEQ = [ ((Du * A) + (T * Mn)) / ln(L) * Cc ] * Csa - Pd
        """
        title_clean = str(title).lower()
        l_val = len(title_clean)
        if l_val <= 1: return 0.0

        # Narrative Tension (T)
        t_score = 1.0 if any(verb in title_clean for verb in self.TENSION_VERBS) else 0.0

        # Novelty Multiplier (Mn)
        mn_score = 1.0
        for term, multiplier in self.NOVEL_TERMS.items():
            if term in title_clean:
                mn_score = max(mn_score, multiplier)

        # Semantic Density (Du) - Simple proxy based on colon or structural complexity
        # In a full NLP implementation, this uses spaCy dependency parsing
        du_score = float(len(re.split(r':|;', title_clean)))

        # Doctrinal Anchor (A)
        a_score = 1.0

        # Specialty Alignment (Csa) - Derived from W&L Rank
        # Top 20 journals usually have higher gatekeeper friction
        try:
            rank_int = int(journal_rank)
            c_sa = 1.1 if rank_int <= 20 else 1.0
        except:
            c_sa = 1.0

        # Dilution Penalty (Pd) - Penalty if Du > 2
        p_d = 0.5 * (du_score - 2) if du_score > 2 else 0.0

        # Clarity Coefficient (Cc) - Hardcoded at 0.9 for baseline test
        c_c = 0.9

        numerator = (du_score * a_score) + (t_score * mn_score)
        denominator = math.log(l_val)

        teq = ((numerator / denominator) * c_c) * c_sa - p_d
        return round(teq, 4)

    def scrape_volume(self, issn: str, volume: str, journal_display_name: str) -> pd.DataFrame:
        """
        Performs the Meso-level extraction via Crossref API.
        Includes all types (Article, Note, Other) for untruncated analysis.
        """
        print(f"Scraping {journal_display_name} Vol {volume}...")

        # In a real-world scenario, you'd resolve ISSN via the Source of Truth
        url = f"https://api.crossref.org/journals/{issn}/works"
        params = {"filter": f"volume:{volume}", "rows": 100}

        try:
            response = requests.get(url, params=params, timeout=15)
            if response.status_code != 200:
                print(f"API Error: {response.status_code}")
                return pd.DataFrame()

            items = response.json().get("message", {}).get("items", [])
            metadata = self.get_journal_metadata(journal_display_name)

            records = []
            for item in items:
                title = item.get("title", [""])[0]
                authors_list = item.get("author", [])
                author_str = ", ".join([f"{a.get('given','')} {a.get('family','')}" for a in authors_list]) or "Anonymous"

                # Tagging and Scoring
                pub_code, other_desc = self.categorize_publication(title, author_str)
                teq = self.calculate_teq_2_2(title, metadata.get('rank'))
                cites = item.get("is-referenced-by-count", 0)

                records.append({
                    "Journal": journal_display_name,
                    "WL_Rank": metadata.get('rank'),
                    "WL_Impact": metadata.get('impact_factor'),
                    "Title": title,
                    "Author": author_str,
                    "Pub_Type_Code": pub_code,
                    "Other_Desc": other_desc,
                    "TEQ_Score": teq,
                    "Crossref_Cites": cites
                })

            return pd.DataFrame(records)

        except Exception as e:
            print(f"Scrape failed: {e}")
            return pd.DataFrame()

# ==========================================
# TEST RUN / EXECUTION
# ==========================================

if __name__ == "__main__":
    # Path to the file you uploaded
    engine = TEQProjectEngine("LawJournals.csv")

    # Demonstration Scrape: Columbia Law Review (ISSN 0011-0698)
    # We scrape Vol 123 to capture modern trends
    results = engine.scrape_volume("0011-0698", "123", "Columbia Law Review")

    if not results.empty:
        print("\n--- SAMPLE EXTRACTION RESULTS ---")
        # Display first 5 rows with key metrics
        print(results[["Title", "Pub_Type_Code", "TEQ_Score", "Crossref_Cites"]].head())

        # Export for external regression analysis (minimizing error term epsilon)
        results.to_csv("TEQ_Batch_001_Columbia.csv", index=False)
        print("\nBatch saved as TEQ_Batch_001_Columbia.csv")